name: arabic_listener
description: "Translates Arabic"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  speech_to_text: 6.6.1
  permission_handler: 11.3.1
  convert:
  flutter:
    sdk: flutter
  flutter_js: ^0.8.0
  path: ^1.9.0
  toggle_switch: ^2.3.0
  collection: 
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/